wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684848894.310746
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 17
      - 23
      - 24
      - 34
      - 35
      - 37
      4: 3.9.16
      5: 0.15.3
      8:
      - 3
      - 8
      - 13
